apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
    app.kubernetes.io/name: proxy
spec:
  containers:
  - image: bobmilk4/node-web-app:latest
    name: nodewebapp
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always